service: prediction

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

  stage: dev
  region: us-east-2
  profile: aiProfile

  environment:
    AWS_DEFAULT_REGION: ${ssm:boto3DefaultRegion}
    AWS_ACCESS_KEY_ID: ${ssm:accessKeyId}
    AWS_SECRET_ACCESS_KEY: ${ssm:secretAccessKey}

functions:
  predict:
    handler: handler.predict
    events:
      -http:
        method: post
        cors: true
        path: predict
