service: prediction

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules:
    forceExclude:
        - aws-sdk

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 256
  timeout: 12

  stage: dev
  region: us-east-2
  profile: aiProfile

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:aws:s3:::antonsemenov-ai-files/*"
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::antonsemenov-ai-files/*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: "*"

  # environment:
  #   AWS_DEFAULT_REGION: ${ssm:boto3DefaultRegion}
  #   AWS_ACCESS_KEY_ID: ${ssm:accessKeyId}
  #   AWS_SECRET_ACCESS_KEY: ${ssm:secretAccessKey}

functions:
  predict:
    handler: handler.predict
    events:
      - http:
          method: post
          cors: true
          path: predict
  sendemail:
    handler: handler.sendErrorEmail
    events:
      - http:
          method: post
          cors: true
          path: sendemail
