
service: lambda-python

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    zip: true

provider:
  name: aws
  runtime: python2.7

  stage: dev
  region: us-east-2
  profile: aiProfile

  environment:
    AWS_DEFAULT_REGION: ${ssm:boto3DefaultRegion}
    AWS_ACCESS_KEY_ID: ${ssm:accessKeyId}
    AWS_SECRET_ACCESS_KEY: ${ssm:secretAccessKey}

functions:
  keras:
    handler: handler.keras
